apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
      - name: name
        image: tuapuikia/demoapp:latest
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 100m
            memory: 200Mi
        ports:
        - containerPort: 8080
        env:
        - name: appname
          value: "KRAKEN"
---
apiVersion: v1
kind: Service
metadata:
  name: demo-app
  namespace: default
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: demo-app
